# This is a basic workflow to help you get started with Actions

name: Scrape

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    schedule:
        - cron: "15 4/12 * * *"
    push:
        branches:
            - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Run a multi-line script
              run: |
                  node functions/scraper/scraper-cli.js
                  git config --local user.email "tyrese@github.com"
                  git config --local user.name "GitHub Action test"
                  git add .
                  git commit -m "Scrape"
            - name: Push changes # push the output folder to your repo
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
